public class KICreator {
	public static String[] createKIMoves() {
		String[] instructions = new String[49];
		instructions[0] = "A1";
		instructions[1] = "A2";
		instructions[2] = "A3";
		instructions[3] = "A4";
		instructions[4] = "A5";
		instructions[5] = "A6";
		instructions[6] = "A7";
		instructions[7] = "B1";
		instructions[8] = "B2";
		instructions[9] = "B3";
		instructions[10] = "B4";
		instructions[11] = "B5";
		instructions[12] = "B6";
		instructions[13] = "B7";
		instructions[14] = "C1";
		instructions[15] = "C2";
		instructions[16] = "C3";
		instructions[17] = "C4";
		instructions[18] = "C5";
		instructions[19] = "C6";
		instructions[20] = "C7";
		instructions[21] = "D1";
		instructions[22] = "D2";
		instructions[23] = "D3";
		instructions[24] = "D4";
		instructions[25] = "D5";
		instructions[26] = "D6";
		instructions[27] = "D7";
		instructions[28] = "E1";
		instructions[29] = "E2";
		instructions[30] = "E3";
		instructions[31] = "E4";
		instructions[32] = "E5";
		instructions[33] = "E6";
		instructions[34] = "E7";
		instructions[35] = "F1";
		instructions[36] = "F2";
		instructions[37] = "F3";
		instructions[38] = "F4";
		instructions[39] = "F5";
		instructions[40] = "F6";
		instructions[41] = "F7";
		instructions[42] = "G1";
		instructions[43] = "G2";
		instructions[44] = "G3";
		instructions[45] = "G4";
		instructions[46] = "G5";
		instructions[47] = "G6";
		instructions[48] = "G7";
		return instructions;
	}
}
